#define SYSCALL_PRINT_STRING 1
#define SYSCALL_GET_TIME 2

#define SYSCALL_MALLOC 10
#define SYSCALL_REALLOC 11
#define SYSCALL_FREE 12

#define SYSCALL_GETCHAR 30
#define SYSCALL_CLEAR 31

#define SYSCALL_POWER_OFF 100
#define SYSCALL_REBOOT 101
